const CatgoryActionTypes = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY'
}

export default CatgoryActionTypes