const constants = {
    CREATE_PRODUCT : 'CREATE_PRODUCT',
    EDIT_PRODUCT : 'EDIT_PRODUCT',
    EDIT_IMAGES : 'EDIT_IMAGES',
    UPLOAD_PRODUCT : 'UPLOAD_PRODUCT',
    DOWNLOAD_PRODUCT : 'DOWNLOAD_PRODUCT',
    MISSING_INFORMATION: 'LA INFORMACIÓN PROPORCIONADA ESTA INCOMPLETA'
} 

export default constants;