const constants = {
    CREATE_PRODUCT : 'CREATE_PRODUCT',
    EDIT_PRODUCT : 'EDIT_PRODUCT',
    EDIT_IMAGES : 'EDIT_IMAGES',
    UPLOAD_PRODUCT : 'UPLOAD_PRODUCT',
    DOWNLOAD_PRODUCT : 'DOWNLOAD_PRODUCT',
    IMAGES_UPLOAD: 'IMAGES_UPLOAD',
    MISSING_INFORMATION: 'LA INFORMACIÓN PROPORCIONADA ESTA INCOMPLETA',
    CATEGORY_LABEL: 'Categoría:'
} 

export default constants;