const ProductActionTypes = {
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    SET_SHOW_EDIT_WINDOW: 'SET_SHOW_EDIT_WINDOW',
    SET_EDIT_OPTIONS: 'SET_EDIT_OPTIONS'
}

export default ProductActionTypes